name: warmup-vercel-cache
on:
  schedule:
    - cron: '15 0,12 * * *'
jobs:
  warmup_vercel_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Warm up
        run: |
          curl 'https://github-readme-stats-teal-iota-47.vercel.app/api?username=h6ah4i&hide=commits&cache_seconds=86400'
          curl 'https://github-readme-stats-teal-iota-47.vercel.app/api/top-langs/?username=h6ah4i&layout=compact&cache_seconds=86400'
